### ISSUE TITLE
Document repo structure

### ISSUE THREAD

**Issue by alambike** [prefapp/firestarter-workflows#1]
We are distributing the dagger workflows as python packages, under the namespace firestarter.

Also the firestarter package has a `cli` subpackage as the entry point for the workflow applications, by default every workflow has the following parameters:
- workflow: name of the workflow package to run (mandatory)
- vars: dict of vars to pass to the workflow application, in toml format  (optional). [You can use toml inline tables](https://toml.io/en/v1.0.0#inline-table)
- secrets: dict with secrets to pass to the workflow application (optional), in toml format
- config_file: str with a local path to a config file (optional)

A project can use the standard firestarter-workflows, adding the firestarter-workflows package as dependency, in its `pyproject.toml`, and defining a poetry script invoking the `firestarter.cli:parse` entrypoint.

Also, you can define your own firestarter workflow application, from the local project, creating a python package complying with the worflow interface:
- Package name: it will be the workflow name
- A run() method exported from the package __init__ accepting the following args:
  - vars: dict 
  - secrets: dict 
  - config_file : str

As every workflow has a set of mandatory and a set of extra dependencies needed, we can configure the group of extra dependencies needed, using the name of the workflow, as the extra group:

https://python-poetry.org/docs/pyproject/#extras

[tool.poetry.group.dev.dependencies]
fastapi = {version="^0.92.0", extras=["all"]}

**Comment by frmadem** [comment]
@alambike following this spec, how a pr-verify example could be defined:

```toml
# pyproject.toml 
[tool.poetry]
name = "firestarter"
version = "0.1.0"
description = ""
authors = []
readme = "README.md"
packages = []

[tool.poetry.dependencies]
python = "^3.11"
firestarter-workflows = "<our version>"

[tool.poetry.scripts]
run = 'firestarter.cli:parse'

```
