### ISSUE TITLE
[BUG] `secrets` in `build_images.yaml` are inherited between flavors

### ISSUE THREAD

**Issue by juanjosevazquezgil** [prefapp/firestarter-workflows#119]
# Motivation
Given this `build_images.yaml` configuration:

```yaml
snapshots:
  flavor:
    dockerfile: Dockerfile
    secrets:
       secret1: value
       secret2: value
     ...

   flavor-2:
     auto: true
```

`flavor-2` will have both `secret1` and `secret2` set with the values of `flavor`, maybe even `dockerfile` (this needs to be tested further. It may be a default path rather than inheritance from the other flavor). This is undesirable because different flavors may have differente secrets and dockerfiles, and when unset the workflow should throw an error.

I personally believe that this happens because this values (at least the secrets) are saved to temporary files which persist between flavors in the building process. Further discussion with @tonirvega and @jalvarezit suggest this may not be the case though

### Acceptance criteria
- [ ] The workflow throws an error when `dockerfile` or a secret needed by the dockerfile are missing from `build_images.yaml`
