### ISSUE TITLE
[BUG] `build_images.yaml` accepts duplicate values for flavors 

### ISSUE THREAD

**Issue by juanjosevazquezgil** [prefapp/firestarter-workflows#123]
# Motivation
Currently `build_images.yaml` allows the following config as valid:

```yaml
snapshots:
  default:
    [values1]
  default:
    [values2]
```

When building, a `default` flavor will be built with `[values2]`. We want to disallow this as it's very error prone and has no practical use

### Acceptance criteria
- [ ] The python code checks whether a specific flavor has been specified twice or more times, and throws an error when that happens
- [ ] Team acceptance
