### ISSUE TITLE
[state-repo] Dejar los artefactos renderizados en la rama deployment

### ISSUE THREAD

**Issue by jalvarezit** [prefapp/firestarter-workflows#125]
También habría que crear una rama *deployment* con una dettached HEAD donde se suben los resultados del helmfile template en su propia carpeta siguiendo el siguiente formato:

```md
apps
└── tenant
    └── app-name
        └── environment
            ├── deployment.yaml
            └── configmap.yaml
sys-services
└── sys-service-name
    └── cluster-name
```

> Tiene que tener la flag de sops_enabled a false para evitar hacer leak de los secretos

_Originally posted by @jalvarezit in https://github.com/prefapp/features/issues/284#issuecomment-2332300334_
            
```[tasklist]
### Tasks
- [ ] https://github.com/prefapp/firestarter-workflows/issues/164
- [ ] https://github.com/prefapp/features/issues/295
```

**Comment by alambike** [comment]
Some interesting details:
Helmfile has an `output-dir` parameter that will allow us to render all the releases artifacts in a folder, for example:

```
helmfile -e dev template --output-dir dev/artifacts
```

But, when we apply a [kustomization](https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/patches/), following [this docs](https://helmfile.readthedocs.io/en/latest/advanced-features/#adhoc-kustomization-of-helm-charts), with `strategicMergePatches` or `jsonPatches`, **the results of the previous `helmfile template` command is only one file named `patched_resources.yaml`.

We could apply this `yq` command to split this file:
```
yq -s '.metadata.name' patched_resources.yaml && rm -f patched_resources.yaml
```

**Comment by jalvarezit** [comment]
También tenemos que añadir la posibilidad de añadir `sys-apps` donde se guardarían los valores de las charts que renderizan workflows de argocd:
```
sys-apps
└── tenant
    └── app-name
        └── environment
            ├── deployment.yaml
            └── configmap.yaml
```

**Comment by tonirvega** [comment]
Dejo por aquí un acercamiento para la coordenada del k8s cluster, no sé si puede ser una opción válida.

```
.
└── apps/
    └── <tenant>/
        └── <app>/
            └── <env>/
                └── <cluster>/
                    ├── Artifact.a.yaml
                    └── Artifact.b.yaml
``` 

y la ApplicationSet así ?

```
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: apps
spec:
  generators:
    - git:
        repoURL: 'https://github.com/councilbox/<tenant>-state.git'
        branch: 'deployment'
        directories:
          - path: '/apps/*/*/*/*'
  template:
    metadata:
      name: '{{path.segment.0}}-{{path.segment.1}}-{{path.segment.2}}'
    spec:
      project: default
      source:
        repoURL: 'https://github.com/councilbox/state-argocd.git'
        targetRevision: 'deployment'
        path: '{{path.segment.0}}/{{path.segment.1}}/{{path.segment.2}}/{{path.segment.3}}'    
      destination:
        server: '{{path.segment.3}'
        namespace: '{{path.segment.0}}-{{path.segment.1}}-{{path.segment.2}}'
      syncPolicy:
        automated:
          prune: true
```

**Comment by tonirvega** [comment]
@jalvarezit @alambike a ver qué os parece.

Viendo las posibilidades que tenemos con los ApplicationSets, creo que este el mejor acercamiento. Podemos gobernar desde state-argocd a qué cluster se publica cada una de las apps de forma dinámica, con una única aplicationset por state repo. Esto se puede realizar gracias a la interpolación de los `values` en el generador de git.

Estos valores tienen que ser clave-valor, no podemos meter objetos complejos, pero pienso que es lo más sencillo y encaja en todas las posibilidades. Después en la propiedad `template.spec.destination.server` se accede por el segment del environment para sacar el cluster correspondiente de los values. Lo he podido testear en nuestro cluster de pruebas.


Esto también ayuda a @jalvarezit para que no tenga que modificar su implementación a la hora de renderizar.

```yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: test-state-apps
  namespace: argocd
spec:
  generators:
  - git:
      files:
      - path: apps/*/*/*
      repoURL: https://github.com/firestartr-test/test-state.git
      revision: HEAD
      values:
        dev: https://kubernetes.default.svc  # clave valor
        pre: https://kubernetes.default.svc
        pro: https://kubernetes.default.svc
  goTemplate: true
  goTemplateOptions:
  - missingkey=error
  template:
    metadata:
      name: '{{index .path.segments 1}}-{{index .path.segments 2}}-{{index .path.segments 3}}'
    spec:
      destination:
        namespace: '{{index .path.segments 1}}-{{index .path.segments 2}}-{{index .path.segments 3}}'
        server: '{{index .values (index .path.segments 3)}}' # <- acceso a los values mediante el segment 3, que es el environment
      project: default
      source:
        path: '{{index .path.segments 0}}/{{index .path.segments 1}}/{{index .path.segments 2}}/{{index .path.segments 3}}'
        repoURL: https://github.com/firestartr-test/test-state.git
        targetRevision: HEAD
      syncPolicy:
        automated:
          prune: true
        syncOptions:
        - CreateNamespace=true
 ```
 
 ##poc en eks con dos despliegues reales

### state repo
state repo de prueba -> https://github.com/firestartr-test/test-state/tree/main/apps/tenant-1
![image](https://github.com/user-attachments/assets/2912eca4-442d-49ec-9805-e53f0260681d)

### artefactos en k9s
![image](https://github.com/user-attachments/assets/2249a3d9-3e83-4a3a-ae46-2822df4861c7)

 ### aplications generadas dinámicamente
![image](https://github.com/user-attachments/assets/b796b29a-6480-43ed-9be3-8b6b14666a77)

**Comment by tonirvega** [comment]
```yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: <state-repo>-<tenant>-apps
  namespace: argocd
spec:
  generators:
  - git:
      files:
      - path: apps/other/*/*<cluster>/*
      repoURL: https://github.com/firestartr-test/test-state.git
      revision: HEAD
      values:
        corpme-predev-aks: https://corpme-predev.default.svc
        corpme-pro: https://corpme-pro.default.svc
  goTemplate: true
  goTemplateOptions:
  - missingkey=error
  template:
    metadata:
      name: '{{index .path.segments 1}}-{{index .path.segments 2}}-{{index .path.segments 4}}'
    spec:
      destination:
        namespace: '{{index .path.segments 1}}-{{index .path.segments 2}}-{{index .path.segments 4}}'
        server: '{{index .values (index .path.segments 3))}}'
      project: <state-repo>-<tenant>-'{{index .path.segments 2}}'-'{{index .path.segments 4}}'
      source:
        path: '{{index .path.segments 0}}/{{index .path.segments 1}}/{{index .path.segments 2}}/{{index .path.segments 4}}'
        repoURL: https://github.com/firestartr-test/test-state.git
        targetRevision: HEAD
      syncPolicy:
        automated:
          prune: true
        syncOptions:
        - CreateNamespace=true
```

**Comment by tonirvega** [comment]
# PoC en Amazon EKS: Project de ArgoCD por cada cluster

## 1. Repo de gitops
https://github.com/firestartr-test/test-state
Estructura de carpetas:

```shell
├── apps
│   └── my-eks <-cluster
│       └── tenant-1
│           ├── app-1
│           │   └── dev
│           │       └── pod.yaml
│           ├── app-2
│           │   └── pre
│           │       └── pod.yaml
│           └── app-3
│               └── pre
│                   └── pod.yaml
```

## 2. ApplicationSet

```yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  #<state-repo>-<tenant>-<cluster-id>-apps
  name: test-state-tenant-1-my-eks-apps
  namespace: argocd
spec:
  generators:
  - git:
      files:
      - path: apps/*/*/*/*
      repoURL: https://github.com/firestartr-test/test-state.git
      revision: HEAD
      values:
        my-eks: https://kubernetes.default.svc
  goTemplate: true
  goTemplateOptions:
  - missingkey=error
  template:
    metadata:
      name: '{{index .path.segments 2}}-{{index .path.segments 3}}-{{index .path.segments 4}}'
    spec:
      destination:
        namespace: '{{index .path.segments 2}}-{{index .path.segments 3}}-{{index .path.segments 4}}'
        server: '{{index .values (index .path.segments 1)}}' # <- cluster url
      project: '{{index .path.segments 1}}' # <- cluster id
      source:
        path: '{{index .path.segments 0}}/{{index .path.segments 1}}/{{index .path.segments 2}}/{{index .path.segments 3}}/{{index .path.segments 4}}'
        repoURL: https://github.com/firestartr-test/test-state.git
        targetRevision: HEAD
      syncPolicy:
        automated:
          prune: true
        syncOptions:
        - CreateNamespace=true
```

## 3. ArgoProject

```yaml
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: my-eks
  namespace: argocd
spec:
  description: My EKS Apps
  sourceRepos:
  - "https://github.com/firestartr-test/test-state.git"
  destinations:
  - namespace: "{tenant-1-app-1-dev,tenant-1-app-2-pre}" # <- namespaces permitidos 
    server: https://kubernetes.default.svc
```

## 4. Control por parte de plataforma

Lo que conseguimos con ésta estructura de directorios, es que el `ApplicationSet`  genere los namespaces basándose en los paths del repo de gitops, y por tanto, podemos añadir un control de despliegue mediante el `AppProject` de forma específica por cluster, con una lista de namespaces permitidos. 

Por tanto si alguien añade una app en los directorios del repo de gitops sin pasar por el control de plataforma, el ApplicationSet tratará de crear un namespace con los directorios en los que el dessarrollador haya dejado sus artefactos, pero el  AppProject va a parar el despliegue, ya que ese namespace generado no está entre los permitidos.

#### 4.1 Ejemplo de despliegues permitidos

**Aplicación 1**
![image](https://github.com/user-attachments/assets/aaefff4b-e1e9-477e-82f3-14350498824e)
**Aplicación 2**
![image](https://github.com/user-attachments/assets/4cfe0e4e-e40e-459b-b4c7-f27e25b5e519)

Argo Applications generadas
![image](https://github.com/user-attachments/assets/39dde9e3-f80e-4e75-be67-36d652d6d860)

Despliegue de los artefactos de kuberenetes con su namespace dinámicamente generado
![image](https://github.com/user-attachments/assets/cfa7621a-01a9-4362-ac11-d1675b98e7de)

#### 4.2 Ejemplo de despliegue no permitido

La siguiente aplicación no ha sido dado de alta en los namespaces disponibles del AppProject, por tanto el namespace que va a generar dinámicamente la ApplicationSet no va a ser validado por éste.
![image](https://github.com/user-attachments/assets/f70124a4-9ece-44c2-81d2-1cf93cf1cf06)

Lo que sucede en este caso es que la Application se genera pero no llega a desplegarse, queda estado Unknown
![image](https://github.com/user-attachments/assets/d748dcc3-3dbe-4fa7-bc7f-7c7c923bc816) 

y si accedemos al artefacto en kubernetes podemos apreciar el log de error

![image](https://github.com/user-attachments/assets/b9e0f282-d45b-4184-aaa6-c6dd88962bc5)
