### ISSUE TITLE
Engadir make_dispatches ó novo workflow de build-images

### ISSUE THREAD

**Issue by juanjosevazquezgil** [prefapp/firestarter-workflows#55]
Relacionado con #45

É necesario mellorar a implementación deses workflows para que inclúan o _step_ de `make_dispatches` presente no workflow actual do repo `gitops-k8s`.

Para que funcione cos `extra_registries` da nova configuración, proponse facer un arquivo `make_dispatches.yaml` onde cada entrada de `extra_registries` tería asociado o nome do seu repo de estado. Formarase unha matrix con estas dúas configuracións, e con ela executarase o _step_ de `make_dispatches` tantas veces como sexa necesario.

Exemplo de `make_dispatches.yaml`:

```yaml
dispatches:
  - registry: cbxacr
    state_repos:
      - cbx-state
  - registry: acrreleases
    state_repos:
      - cbx-state
      - state-corpme
      - state-giss
  - registry: acrnoreleases
    state_repos:
      - cbx-state
      - state-corpme
      - state-giss
```
