### ISSUE TITLE
Create and upgrade make_dispatches workflow

### ISSUE THREAD

**Issue by juanjosevazquezgil** [prefapp/firestarter-workflows#70]
# Motivation
We want to make a make_dispatches workflow that is both reusable and manually callable, so that our other workflows can use it and users can dispatch images without building them from scratch when needed. To this end, the following workflow inputs are proposed:

```yaml
name: Make dispatches

on:
  workflow_dispatch:
    type:
      type: choice
      description: Dispatches to make (releases, snapshots or both)
      options:
        - *
        - releases
        - snapshots
      required: true
      default: *
    flavor:
      type: string 
      description: Filter dispatches based on flavor (one (alone), several(separated by commas) or * (all))
      required: true
      default: "default"
    state-repo:
      type: string
      description: Filter dispatches based on state repos of the flavor (one (alone), several(separated by commas) or * (all))
      required: true
      default: "*"
    # If specified, only this image will be calculated and dispatched (deployment_dispatch is not used, we calculate it inside this workflow)
    version:
      type: string
      description: Release tag or sha commit
      required: false
      default: ""

jobs:
  <job that calls make_dispatches with the user's input, when version is not specified>

  <job that calculates and dispatches the version specified by the user, the dispatches it>
```

Some changes to the `make_dispatches` action may be needed

### Acceptance criteria
- [x] A make_dispatches workflow is created
- [x] The workflow can be called manually specifying a type, flavor and state-repo
- [x] The workflow can be called manually specifying a type, flavor and version
- [x] The workflow can be called automatically by another workflow
- [x] Team acceptance
