### ISSUE TITLE
Add login to ACR Registries to the make_dispatches workflow

### ISSUE THREAD

**Issue by alambike** [prefapp/firestarter-workflows#80]
### Motivation
To address https://github.com/prefapp/action-make-state-repos-dispatches/pull/10, we need to add the login to the registries configured in the build-images workflow.

The default org Docker registries can be obtained from the specific variables (vars.DOCKER_REGISTRY_RELEASES, vars.DOCKER_REGISTRY_SNAPSHOTS ), but the extra-registries need to be obtained from the `build-images.yml` config file

```yaml
     - name: Get registries
       # Default org registries + extra registries 

      - name: Azure CLI script
        run: |
         for registry in @$REGISTRIES; do
             az acr login --name $registry
         done

      - name: Dispatch changes
        uses: prefapp/action-make-state-repos-dispatches@feat/5-check-image-existence
        env:
          DEBUG: '*'
        with:
          dispatches_file: ${{ inputs.dispatches_file }}
          token: ${{ secrets.TEST_TOKEN }}
          dispatch_type: ${{ inputs.dispatch_type }}
          flavors: ${{ inputs.flavors }}
          state_repo: ${{ inputs.state_repo }}
          default_releases_registry: ${{ vars.DOCKER_REGISTRY_RELEASES }}
          default_snapshots_registry: ${{ vars.DOCKER_REGISTRY_SNAPSHOTS }}
          reviewers: ${{ github.actor }}
          # registry_base_paths: ${{ vars.DOCKER_REGISTRIES_BASE_PATHS }}
  ```
