### ISSUE TITLE
Add workflow tests

### ISSUE THREAD

**Issue by itasahobby** [prefapp/firestarter-workflows#9]
# Motivation

To make sure the workflow works as expected we should add tests.

For instance to test build-images workflow we could create a different step for publishing:

https://github.com/prefapp/firestarter-workflows/blob/d4e114b1ac185c237e4336d18f081b1262cb0307/firestarter/workflows/build_images/build_images.py#L46C10-L57

Then we could intercept the build process and analyze the output container to make sure the structure is correct.

# Acceptance criteria

- [ ] There is a test for build-images workflow
- [ ] Team acceptance

**Comment by itasahobby** [comment]
We could attempt to create a `ContainerStructureTest` class based on google [google project](https://github.com/GoogleContainerTools/container-structure-test).

Starting with the following definition:
```yaml
commandTests:
  - name: "gunicorn flask"
    setup: [["virtualenv", "/env"], ["pip", "install", "gunicorn", "flask"]]
    command: "which"
    args: ["gunicorn"]
    expectedOutput: ["/env/bin/gunicorn"]
fileExistenceTests:
  - name: 'Root'
    path: '/'
    shouldExist: true
    permissions: '-rw-r--r--'
    uid: 1000
    gid: 1000
    isExecutableBy: 'group'
fileContentTests:
  - name: 'Debian Sources'
    path: '/etc/apt/sources.list'
    expectedContents: ['.*httpredir\.debian\.org.*']
    excludedContents: ['.*gce_debian_mirror.*']
metadataTest:
  envVars:
    - key: foo
      value: baz
  labels:
    - key: 'com.example.vendor'
      value: 'ACME Incorporated'
    - key: 'build-date'
      value: '^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d{6}$'
      isRegex: true
  exposedPorts: ["8080", "2345"]
  volumes: ["/test"]
  entrypoint: []
  cmd: ["/bin/bash"]
  workdir: "/app"
  user: "luke"
```
