### ISSUE TITLE
New `manual` parameter to skip flavor image build, by default to `false`

### ISSUE THREAD

**Issue by alambike** [prefapp/firestarter-workflows#90]
```yaml
snapshots:
  corpme-dev:
    build_args:
      VITE_API_URL: "https://rivulet-api.corpme.dev.councilbox.com/graphql"
      VITE_API_EXPRESS_URL: "https://rivulet-api.corpme.dev.councilbox.com"
    dockerfile: docker/Dockerfile
    manual: true (default to false)
```
