### ISSUE TITLE
WIP - [build-images] Add alternate mode to build docker images

### ISSUE THREAD

**Issue by alambike** [prefapp/firestarter-workflows#97]
### Use case
As a platform engineer I want to pave and improve de DX by creating an alternat way to build the project imagen, without the need of an Dockerfile, and also improve the control over the images that the organization teams can use, and how they are built.

To achieve that we would need some refactor in config file to add new parameters available, for flavor:

```yaml
fs_builder:
  technology: node:18
  template: spa
  extra_packages: ["git"]  # Extra system packages to install
  build_commands: [npm ci && npm run build] # commands to build the artifact to install in the image
  build_args: ["VITE_API_URL=https://my-url"]  # Arguments to pass to the build system
```

### Corollary
The base image, which the platform team will create and maintain, is actually composed of 2:
one for run and one for build, for the previous example:
- spa-node:18-run
- spa-node:18-build

We would follow a scheme like the following implemented in Dagger, for the construction of the artifact, using an equivalent dagger workflow, to the expressed Dockerfile

FROM  spa-node:18-build AS BUILD_IMAGE

RUN yarn install

RUN yarn build 

FROM node:18-buster-slim

RUN apt-get update && apt-get install -y \
    gconf-service libasound2 libatk1.0-0 libatk-bridge2.0-0 \
    libgbm-dev libc6 libcairo2 libcups2 libdbus-1-3 libexpat1 libfontconfig1 \
    libgcc1 libgconf-2-4 libgdk-pixbuf2.0-0 libglib2.0-0 libgtk-3-0 \
    libnspr4 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 \
    libx11-xcb1 libxcb1 libxcomposite1 libxcursor1 libxdamage1 \
    libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 \
    libxtst6 ca-certificates fonts-liberation libappindicator1 \
    libnss3 lsb-release xdg-utils wget default-jre \
    locales locales-all \
    && apt-get autoremove -y \
    && apt-get clean -y \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* 

ENV LC_ALL en_US.UTF-8
ENV LANG en_US.UTF-8
ENV LANGUAGE en_US.UTF-8

WORKDIR /app

COPY --from=BUILD_IMAGE /app/dist dist

COPY --from=BUILD_IMAGE /app/node_modules node_modules

COPY --from=BUILD_IMAGE /app/src/templates src/templates

COPY --from=BUILD_IMAGE /app/src/locales src/locales

COPY --from=BUILD_IMAGE /app/src/certs src/certs

COPY --from=BUILD_IMAGE /app/src/static src/static

RUN chown -R node:node /app

USER node

ENTRYPOINT [ "node", "--enable-source-maps", "dist/server.js" ]

**Comment by tonirvega** [comment]
``` yaml
snapshots:
  default:
    auto: true
    dockerfile: docker/Dockerfile -> No sería compatible Dockerfile + fs_builder
    fs_builder:
      technology: spa-node:18-rev23
      template: spa-rev3
      template_args: 
         REWRITE_RULES : {}
      extra_packages: ["git"]  # Extra system packages to install
      build_commands: [npm ci && npm run build] # commands to build the artifact to install in the image
      build_args: ["VITE_API_URL=https://my-url"]  # Arguments to pass to the build system
      
    extra_registries:
      - name: cbxacr.azurecr.io
        repository: cbx/councilbox-server
        auth_strategy: azure_oidc
        
releases:
  default:
    auto: true
    dockerfile: docker/Dockerfile
    extra_registries:
      - name: cbxacr.azurecr.io
        repository: cbx/councilbox-server
        auth_strategy: azure_oidc
 ```
